services:
  chalk:
    build:
      context: .
      args:
        CHALK_BUILD: ${CHALK_BUILD:-debug}
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  chalk-compile:
    build:
      context: .
      target: compile
    command: sh -c "nimble debug"
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  chalk-config-compile:
    build:
      context: .
      dockerfile: docker/Dockerfile.chalk-config
      target: config-tool-compile
    command: sh -c "python chalk-config/chalkconf.py"
    volumes:
      - $PWD/config-tool:/config-tool
      - $PWD/.config-tool-bin:/config-bin
    environment:
      TERM: "xterm-256color"
      COLORTERM: "truecolor"
      CHALK_BINARIES_ARE_LOCAL: 1
    depends_on:
      - chalk-compile

  chalk-config:
    build:
      context: .
      dockerfile: docker/Dockerfile.chalk-config
    environment:
      TERM: "xterm-256color"
      COLORTERM: "truecolor"
      CHALK_BINARIES_ARE_LOCAL: 1
    volumes:
      - $PWD/.config-tool-bin:/config-bin
      - $PWD/config-tool-outdir:/outdir/

  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.pytests
    command: pytest tests
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.aws:/root/.aws
    working_dir: $PWD
    environment:
      AWS_PROFILE: ${AWS_PROFILE:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
    depends_on:
      - chalk-compile
