networks:
  chalk:

services:
  chalk:
    build:
      context: .
      args:
        CHALK_BUILD: ${CHALK_BUILD:-debug}
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  chalk-compile:
    build:
      context: .
      target: compile
    command: sh -c "nimble debug"
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  chalk-config-compile:
    build:
      context: .
      dockerfile: docker/Dockerfile.chalk-config
      target: config-tool-compile
    command: sh -c "python chalk-config/chalkconf.py"
    volumes:
      - $PWD/config-tool:/config-tool
      - $PWD/.config-tool-bin:/config-bin
    environment:
      TERM: "xterm-256color"
      COLORTERM: "truecolor"
      CHALK_BINARIES_ARE_LOCAL: 1
    depends_on:
      - chalk-compile

  chalk-config:
    build:
      context: .
      dockerfile: docker/Dockerfile.chalk-config
    environment:
      TERM: "xterm-256color"
      COLORTERM: "truecolor"
      CHALK_BINARIES_ARE_LOCAL: 1
    volumes:
      - $PWD/.config-tool-bin:/config-bin
      - $PWD/config-tool-outdir:/outdir/

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      chalk:
        aliases:
          - chalk.crashoverride.local
    ports:
      - 8585:8585
      - 8584:8584
    volumes:
      - $PWD:$PWD
    working_dir: $PWD/server/app
    environment:
      CHALK_API_PARAMS: "--workers=4 --error-logfile=- --access-logfile=- --timeout 30"
      CHALK_API_CERT: ""
      CHALK_API_PORT: "8585"

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $PWD/server/app/db/data:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped

  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.pytests
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.aws:/root/.aws
    working_dir: $PWD/tests
    networks:
      chalk:
        aliases:
          - chalk.crashoverride.local
    environment:
      AWS_PROFILE: ${AWS_PROFILE:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
