services:
  chalk:
    build:
      context: .
      args:
        CHALK_BUILD: ${CHALK_BUILD:-debug}
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  chalk-compile:
    build:
      context: .
      target: compile
    command: sh -c "nimble debug"
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.pytests
    command: pytest tests
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: $PWD
