networks:
  chalk:
    name: chalk-internal-network

services:
  chalk:
    build:
      context: .
      args:
        CHALK_BUILD: ${CHALK_BUILD:-debug}
      target: ${BASE:-ubuntu}
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  chalk-compile-release:
    build:
      context: .
      target: compile
    command: nimble build -d:release
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  chalk-compile:
    build:
      context: .
      target: compile
    command: nimble debug
    working_dir: $PWD
    volumes:
      - $PWD:$PWD

  chalk-config:
    build:
      context: config-tool
    command: python -m chalk_config
    volumes:
      - $PWD/config-tool:/config-tool
      - $PWD/.config-tool-bin:/config-bin
      - $PWD/config-tool-outdir:/outdir/
      - $HOME/.config:/root/.config
    environment:
      TERM: ${TERM:-}
      COLORTERM: ${COLORTERM:-}
      CHALK_BINARIES_ARE_LOCAL: 1

  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $PWD/server/app/db/data:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped

  server:
    image: chalk_local_api_server
    container_name: chalk_local_api_server
    build:
      context: server
    networks:
      chalk:
        aliases:
          - chalk.crashoverride.local
    ports:
      - 8585:8585
      - 8584:8584
    volumes:
      - $PWD:$PWD
    working_dir: $PWD/server/app
    environment:
      CHALK_CERT_PARAMS: ${CHALK_CERT_PARAMS:-}
      CHALK_API_PARAMS: ${CHALK_API_PARAMS:- --access-logfile=- --workers=4 --error-logfile=- --timeout=30}
      CHALK_API_PORT: ${CHALK_API_PORT:-8585}

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5044:5044"
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5044
    networks:
      - chalk

  tests:
    image: chalk_local_tests
    container_name: chalk_local_tests
    build:
      context: tests
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.aws:/root/.aws
    working_dir: $PWD/tests
    networks:
      - chalk
    depends_on:
      - registry
    environment:
      AWS_PROFILE: ${AWS_PROFILE:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      TEST_CERT_FILE: ${TEST_CERT_FILE:-}
      CHALK_CERT_PARAMS: ${CHALK_CERT_PARAMS:-}
      CHALK_API_PARAMS: ${CHALK_API_PARAMS:-}
      CHALK_API_PORT: ${CHALK_API_PORT:-}
      GITHUB_ACTIONS: ${GITHUB_ACTIONS:-}
