name: Setup Release Deps

inputs:
  os:
    description: OS for the release
    required: false
    default: linux
  arch:
    description: Arch for the release
    required: false
    default: amd64
  secrets:
    description: json secrets
    required: true

runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      if: inputs.os == 'linux'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    # buildjet has older version of buildx which is incompatible with bake
    - name: Set up Docker Buildx
      if: inputs.os == 'linux'
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.11.2

    # buildjet has older version of compose which is incompatible with
    # some of the compoase parameters like multiple contexts
    # https://docs.docker.com/compose/install/linux/
    - name: Set up Docker Compose
      if: inputs.os == 'linux' && inputs.arch == 'arm64'
      shell: bash
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-$(uname -m) -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

    - name: Docker info
      if: inputs.os == 'linux'
      shell: bash
      run: |
        docker info
        docker buildx version
        docker compose version

    # buildjet is missing awscli installed
    - name: Set up AWS CLI
      if: inputs.os == 'linux' && inputs.arch == 'arm64'
      shell: bash
      run: |
        python -m pip install awscli
        which aws
        aws --version

    # brew is much faster but if well need to pin nim version
    # we can use this action instead
    # - name: Install Nim
    #   if: inputs.os == 'darwin'
    #   uses: iffy/install-nim@v4
    #   with:
    #     version: 2.0.0

    - name: Install Nim
      if: inputs.os == 'darwin'
      shell: bash
      run: |
        brew install nim

    - name: Check Nim Version
      if: inputs.os == 'darwin'
      shell: bash
      run: |
        nim --version
        nimble --version

    - name: Assume AWS Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ fromJSON(inputs.secrets).AWS_ACCOUNT_ID }}:role/${{ fromJSON(inputs.secrets).CHALK_RELEASE_ROLE }}
        role-session-name: GithubRelease
