name: "Setup Release Deps"

inputs:
  platform:
    description: "OS release is happening for"
    required: false
    default: amd64
  secrets:
    description: "json secrets"
    required: true

runs:
  using: "composite"
  steps:
    # buildjet has older version of buildx which is incompatible with bake
    - name: Set up Docker Buildx
      if: inputs.platform == 'arm64'
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.11.2

    # buildjet has older version of compose which is incompatible with
    # some of the compoase parameters like multiple contexts
    # https://docs.docker.com/compose/install/linux/
    - name: Set up Docker Compose
      if: inputs.platform == 'arm64'
      shell: bash
      run: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-$(uname -m) -o $DOCKER_CONFIG/cli-plugins/docker-compose
        chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

    - name: Docker info
      shell: bash
      run: |
        docker info
        docker buildx version
        docker compose version

    # buildjet is missing awscli installed
    - name: Set up AWS CLI
      if: inputs.platform == 'arm64'
      shell: bash
      run: |
        python -m pip install awscli
        which aws
        aws --version

    - name: Assume AWS Role
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ fromJSON(inputs.secrets).AWS_ACCOUNT_ID }}:role/${{ fromJSON(inputs.secrets).CHALK_RELEASE_ROLE }}
        role-session-name: GithubRelease
