name: release-config
on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  release:
    runs-on: ${{ matrix.builder }}

    outputs:
      chalkversion: ${{ steps.chalkversion.outputs.version }}
      chalkconfigversion: ${{ steps.chalkversion.outputs.chalk_config_version }}

    strategy:
      matrix:
        include:
          - builder: ubuntu-latest
            platform: amd64
          - builder: buildjet-2vcpu-ubuntu-2204-arm
            platform: arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Get chalk version
        id: chalkversion
        run: |
          echo "CHALK_VERSION=$(cat chalk_internal.nimble | grep version | grep "=" | cut -d'"' -f2)" >> "$GITHUB_ENV"
          echo "CHALK_CONFIG_VERSION=$(cat config-tool/chalk-config/chalkconf.py | grep __version__ | grep "=" | cut -d'"' -f2)" >> "$GITHUB_ENV"
          echo "version=$(cat chalk_internal.nimble | grep version | grep "=" | cut -d'"' -f2)" >> "$GITHUB_OUTPUT"
          echo "chalk_config_version=$(cat config-tool/chalk-config/chalkconf.py | grep __version__ | grep "=" | cut -d'"' -f2)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Check versions
        run: |
          echo "Building with the following versions"
          echo ${{ env.CHALK_VERSION }}
          echo ${{ env.CHALK_CONFIG_VERSION }}
          docker info
          docker version

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile.chalk-config
          context: .
          push: true
          provenance: false # https://github.com/docker/buildx/issues/1608
          platforms: linux/${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/chalk-config:latest-${{ matrix.platform }}
            ghcr.io/${{ github.repository_owner }}/chalk-config:${{ env.CHALK_CONFIG_VERSION }}-${{ matrix.platform }}

  manifest:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Create and push manifest images for latest
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: ghcr.io/${{ github.repository_owner }}/chalk-config:latest
          images: ghcr.io/${{ github.repository_owner }}/chalk-config:latest-amd64,ghcr.io/${{ github.repository_owner }}/chalk-config:latest-arm64
          push: true

      - name: Create and push manifest images for specific version
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: ghcr.io/${{ github.repository_owner }}/chalk-config:${{ needs.release.outputs.chalkconfigversion }}
          images: ghcr.io/${{ github.repository_owner }}/chalk-config:${{ needs.release.outputs.chalkconfigversion }}-amd64,ghcr.io/${{ github.repository_owner }}/chalk-config:${{ needs.release.outputs.chalkconfigversion }}-arm64
          push: true
