name: release
on:
  workflow_dispatch:
    inputs:
      BASE:
        type: choice
        description: "whether chalk should be compiled for alpine or ubuntu "
        options:
          - alpine
          - ubuntu
        message:
          required: true
        required: true
        default: "ubuntu"

permissions:
  packages: write
  contents: read

jobs:
  release:
    runs-on: ${{ matrix.builder }}

    strategy:
      matrix:
        include:
          - builder: ubuntu-latest
            platform: amd64
          - builder: buildjet-2vcpu-ubuntu-2204-arm
            platform: arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Get chalk version
        run: |
          echo "CHALK_VERSION=$(cat chalk_internal.nimble | grep version | grep "=" | cut -d'"' -f2)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Check versions
        if: env.CHALK_VERSION != ''
        run: |
          echo "Building with the following versions"
          echo ${{ env.CHALK_VERSION }}
          docker info
          docker version

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile.chalk-${{ inputs.BASE }}
          context: .
          push: true
          provenance: false # https://github.com/docker/buildx/issues/1608
          platforms: linux/${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/chalk:${{ inputs.BASE }}-latest-${{ matrix.platform }}
            ghcr.io/${{ github.repository_owner }}/nim:${{ inputs.BASE }}-${{ env.CHALK_VERSION }}-${{ matrix.platform }}

  manifest:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Create and push manifest images for latest
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: ghcr.io/${{ github.repository_owner }}/chalk:${{ inputs.BASE }}-latest
          images: ghcr.io/${{ github.repository_owner }}/chalk:${{ inputs.BASE }}-latest-amd64,ghcr.io/${{ github.repository_owner }}/chalk:${{ inputs.BASE }}-latest-arm64
          push: true

      - name: Create and push manifest images for specific version
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: ghcr.io/${{ github.repository_owner }}/nim:${{ inputs.BASE }}-${{ env.CHALK_VERSION }}
          images: ghcr.io/${{ github.repository_owner }}/nim:${{ inputs.BASE }}-${{ env.CHALK_VERSION }}-amd64,ghcr.io/${{ github.repository_owner }}/nim:${{ inputs.BASE }}-${{ env.CHALK_VERSION }}-arm64
          push: true
