name: release:config

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:

permissions:
  contents: read
  id-token: write # for aws role
  packages: write

env:
  CHALK_BINARIES_BUCKET: ${{ secrets.CHALK_BINARIES_BUCKET }}

jobs:
  s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: crashappsec/action-checkout@main
        with:
          fetch-depth: 0

      - name: Setup Release Deps
        uses: ./.github/actions/release
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Build Config Package
        working-directory: ./config-tool
        run: |
          make release

      - name: Push Fake PyPI Release To S3
        working-directory: ./config-tool
        run: |
          make upload
