name: release:server

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:

permissions:
  contents: read
  id-token: write # for aws role
  packages: write

env:
  CHALK_BINARIES_BUCKET: ${{ secrets.CHALK_BINARIES_BUCKET }}

jobs:
  binary:
    runs-on: ${{ matrix.builder }}

    strategy:
      matrix:
        include:
          - builder: ubuntu-latest
            platform: amd64
            os: linux
          - builder: buildjet-2vcpu-ubuntu-2204-arm
            platform: arm64
            os: linux

    steps:
      - name: Checkout Code
        uses: crashappsec/action-checkout@main
        with:
          fetch-depth: 0

      - name: Setup Release Deps
        uses: ./.github/actions/release
        with:
          secrets: ${{ toJSON(secrets) }}
          platform: ${{ matrix.platform }}

      - name: Build Server Binary
        working-directory: ./server
        run: |
          make release

      - name: Sanity check
        working-directory: ./server
        run: |
          ./chalkserver --version

      - name: Dist
        working-directory: ./server
        run: |
          make dist

      - name: Upload To S3
        working-directory: ./server
        run: |
          make upload
