name: test

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: crashappsec/action-checkout@main
        with:
          fetch-depth: 0

      - name: Compile chalk
        run: docker-compose run chalk-compile-ubuntu

      - name: Run tests
        run: docker-compose run --rm tests
