name: tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - src/**
      - tests/**
  workflow_dispatch:
    inputs:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

permissions:
  contents: read
  packages: write

jobs:
  pytest:
    runs-on: ubuntu-latest

    if: |
      github.event_name != 'pull_request' || (
        !github.event.pull_request.draft &&
        !contains(github.event.pull_request.body, format('skip:{0}', github.workflow))
      )

    concurrency:
      # only allow one job per PR running
      # older pending jobs will be cancelled not to waste CI minutes
      # cannot use github.job here https://github.com/community/community/discussions/13496
      group: ${{ github.workflow }}-pytest-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Bake Images
        run: |
          docker buildx bake chalk server tests --load

      - name: Compile Chalk
        run: |
          make

      - name: Run tests
        run: |
          make tests args="-nauto"
