name: test

on: pull_request

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: crashappsec/action-checkout@main
        with:
          fetch-depth: 0

      - name: Compile chalk
        run: docker-compose run chalk-compile

      - name: Run tests
        run: docker-compose run --rm tests
