name: version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to bump"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: crashappsec/action-checkout@main
        with:
          fetch-depth: 0

      # need App access token so that push to protected branch
      - name: Generate org-level access token
        id: org-token
        uses: crashappsec/action-github-app-token@main
        with:
          app_id: ${{ secrets.ACTIONS_GITHUB_APP_ID }}
          private_key: ${{ secrets.ACTIONS_GITHUB_APP_PRIVATE_KEY }}

      - name: Configure git
        run: |
          git config --local user.email "ci@crashoverride.com"
          git config --local user.name "${{ github.actor }}"
          git config --local \
            "http.${{ github.server_url }}/.extraheader" \
            "Authorization: basic $(echo -n 'x-access-token:${{ steps.org-token.outputs.token }}' | base64)"

      - name: Bump version
        env:
          COMPOSE_FILE: docker/docker-compose-bump.yml
        run: |
          # patch is the default version to bump in which case omit arg
          # https://github.com/disruptek/bump/issues/19
          docker compose run --rm bump --v $(echo --${{ inputs.version }} | sed 's/--patch//')
